projectApp/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :schedule
  resources :homeworks
  
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

projectApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

projectApp/app/models/homework.rb
class Homework < ApplicationRecord
    validates :hw_name, presence: true
    validates :due_date, presence: true
    validates :time_required, presence: true
end

projectApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

projectApp/app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
    def show
        @homework = Homework.find(params[:id])
    end
    
    def new
        @homework = Homework.new
    end
    
    def create
        @homework = Homework.new(homework_params)
        
        if @homework.save
            redirect_to @homework
        else
            render 'new'
        end
    end
    
    def edit
        @homework = Homework.find(params[:id])
    end
    
    def update
        @homework = Homework.find(params[:id])
        
        if @homework.update(homework_params)
            redirect_to @homework
        else
            render 'edit'
        end
    end
    
    def destroy
        @homework = Homework.find(params[:id])
        @homework.destroy
        
        redirect_to controller: 'schedule'
    end
end

private
    def homework_params
        params.require(:homework).permit(:hw_name, :due_date, :time_required, :note)
    end

projectApp/app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
  def index
    @homework = Homework.all
    @homework_by_date = @homework.group_by(&:due_date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

projectApp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

projectApp/app/helpers/application_helper.rb
module ApplicationHelper
end

projectApp/app/helpers/calendar_helper.rb
module CalendarHelper
    def calendar(date = Date.today, &block)
        Calendar.new(self, date, block).table
    end
    
    class Calendar < Struct.new(:view, :date, :callback)
        HEADER = %w[Sunday Monday Tuesday Wednesday Thrusday Friday Saturday]
        START_DAY = :sunday
        
        delegate :content_tag, to: :view
        
        def table
            content_tag :table, class: "calendar" do
                header + week_rows
            end
        end
        
        def header
            content_tag :tr do
                HEADER.map { |day| content_tag :th, day }.join.html_safe
            end
        end
        
        def week_rows
            weeks.map do |week|
                content_tag :tr do
                    week.map{ |day| day_cell(day) }.join.html_safe
                end
            end.join.html_safe       
        end
        
        def day_cell(day)
            content_tag :td, view.capture(day, &callback), class: day_classes(day)
        end
        
        def day_classes(day)
            classes = []
            classes << "today" if day == Date.today
            classes << "notmonth" if day.month != date.month
            classes.empty? ? nil : classes.join(" ")
        end
        
        def weeks
            first = date.beginning_of_month.beginning_of_week(START_DAY)
            last = date.end_of_month.end_of_week(START_DAY)
            (first..last).to_a.in_groups_of(7)
        end
    end
end

projectApp/app/helpers/homeworks_helper.rb
module HomeworksHelper
end

projectApp/app/helpers/schedule_helper.rb
module ScheduleHelper
end

projectApp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

projectApp/app/views/homeworks/edit.html.erb
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Homework Scheduler</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="welcome.scss">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar"><%= link_to 'Homework Scheduler', controller: 'welcome' %></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Schedule', controller: 'schedule' %></li>
        <li><%= link_to 'Create Homework', new_homework_path %></li>
      </ul>
    </div>
  </div>
</nav>


<h1>Editing homework</h1>
 
<%= form_for :homework, url: homework_path(@homework), method: :patch do |f| %>
 
  <% if @homework.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@homework.errors.count, "error") %> prohibited
        this homework from being saved:
      </h2>
      <ul>
        <% @homework.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :hw_name %><br>
    <%= f.text_field :hw_name %>
  </p>
 
  <p>
    <%= f.label :due_date %>"yyyy-mm-dd"<br>
    <%= f.text_field :due_date %>
  </p>
  
  <p>
    <%= f.label :time_required %><br>
    <%= f.text_field :time_required %>
  </p>
  
  <p>
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', controller: 'schedule' %>

projectApp/app/views/homeworks/new.html.erb
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Homework Scheduler</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="welcome.scss">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar"><%= link_to 'Homework Scheduler', controller: 'welcome' %></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Schedule', controller: 'schedule' %></li>
        <li><%= link_to 'Create Homework', new_homework_path %></li>
      </ul>
    </div>
  </div>
</nav>


<h1>New Homework</h1>
<%= form_for :homework, url: homeworks_path do |f| %>
  
  <% if @homework.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@homework.errors.count, "error") %> prohibited
        this homework from being saved:
      </h2>
      <ul>
        <% @homework.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :hw_name %><br>
    <%= f.text_field :hw_name %>
  </p>
 
  <p>
    <%= f.label :due_date %>"yyyy-mm-dd"<br>
    <%= f.text_field :due_date %>
  </p>
  
  <p>
    <%= f.label :time_required %><br>
    <%= f.text_field :time_required %>
  </p>
  
  <p>
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', controller: 'schedule' %>

projectApp/app/views/homeworks/show.html.erb
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Homework Scheduler</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="welcome.scss">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar"><%= link_to 'Homework Scheduler', controller: 'welcome' %></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Schedule', controller: 'schedule' %></li>
        <li><%= link_to 'Create Homework', new_homework_path %></li>
      </ul>
    </div>
  </div>
</nav>

<p>
    <strong>HW Name</strong>
    <%= @homework.hw_name %>
</p>

<p>
    <strong>Due Date</strong>
    <%= @homework.due_date %>
</p>

<p>
    <strong>Time Required</strong>
    <%= @homework.time_required %>
</p>

<p>
    <strong>Note</strong>
    <%= @homework.note %>
</p>
<td><%= link_to 'Back', controller: 'schedule' %></td>
<td><%= link_to 'Edit', edit_homework_path(@homework) %></td>
<td><%= link_to 'Delete',
                            homework_path(@homework),
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %></td>

projectApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

projectApp/app/views/schedule/index.html.erb
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Homework Scheduler</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="welcome.scss">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar"><%= link_to 'Homework Scheduler', controller: 'welcome' %></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Schedule', controller: 'schedule' %></li>
        <li><%= link_to 'Create Homework', new_homework_path %></li>
      </ul>
    </div>
  </div>
</nav>

<h1>Schedule</h1>

<div id = "schedule">
  <h2 id="month">
    <%= link_to "<", date: @date.prev_month %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to ">", date: @date.next_month %>  
  </h2>
  <%= calendar @date do |date| %>
    <%= date.day %>
    <% if @homework_by_date[date] %>
      <ul>
        <% @homework_by_date[date].each do |homework| %>
          <li><%= link_to homework.hw_name, homework %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>

<%= link_to "Create homework", new_homework_path %>

projectApp/app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Homework Scheduler</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="welcome.scss">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>

<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar" id="myNavbar"><%= link_to 'Homework Scheduler', controller: 'welcome' %></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Schedule', controller: 'schedule' %></li>
        <li><%= link_to 'Create Homework', new_homework_path %></li>
      </ul>
    </div>
  </div>
</nav>

<!-- First Container -->
<div class="container-fluid bg-1 text-center">
  <h3 class="margin">Welcome!</h3>
  <p>Welcome to our homework scheduler, here you can input your homework and have it displayed in a calendar.</p>
</div>

<!-- Third Container (Grid) -->
<div class="container-fluid bg-3 text-center">    
  <h3 class="margin">Making your life easier as a student.</h3>
  <%= image_tag "/unc.jpg", class: "img-responsive margin", class:"college" %></br>
  <h3 class="margin">Is what we are about.</h3><br>
  <div class="row">
    <div class="col-sm-4"> 
      <p>Calendar</p>
      <%= link_to controller: 'schedule' do %>
         <%= image_tag "/calendar.png", class: "img-responsive margin", class:"schedule" %>
      <% end %>
    </div>
    <div class="col-sm-4">
      <p>Navigation</p>
      <ul class="footer-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'schedule', controller: 'schedule' %></li>
        <li><%= link_to 'create Homework', new_homework_path %></li>
      </ul>
    </div>
    <div class="col-sm-4"> 
      <p>Create Homework</p>
      <%= link_to new_homework_path do %>
         <%= image_tag "/google-form.jpg", class: "img-responsive margin", class:"homework" %>
      <% end %>
    </div>
  </div>
</div>

<!-- Footer -->
<footer class="container-fluid bg-4 text-center">
  <p>Bootstrap Theme Made By <a href="https://www.w3schools.com">www.w3schools.com</a></p> 
</footer>

</body>
</html>